name: ci
on: pull_request
jobs:
  test-all:
    runs-on: self-hosted
    strategy:
      matrix:
        engine: ["python", "ray", "dask"]
        part: ["Reduction_A", "Reduction_B", "Binary", "MapMetadata", "UDF", "Default", "Window", "Indexing", "Iter", "JoinSort", 3]
    env:
      MODIN_ENGINE: ${{matrix.engine}}
      MODIN_MEMORY: 1000000000
    name: test (${{matrix.engine}}, part ${{matrix.part}}, python ${{matrix.python-version}})
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python-version}}
          architecture: "x64"
      - name: Install HDF5
        if: matrix.part == 3
        run: sudo apt update && sudo apt install -y libhdf5-dev
      - run: pip install -r requirements.txt
      - run: bash run-tests.sh ${{matrix.engine}} -k "TestDataFrame${{matrix.part}}"
        if: matrix.part != 3
      - run: python -m pytest modin/pandas/test/test_series.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_rolling.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_concat.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_groupby.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_reshape.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_general.py
        if: matrix.part == 3
      - run: python -m pytest modin/pandas/test/test_io.py
        if: matrix.part == 3
      - run: python -m pytest modin/experimental/pandas/test/test_io_exp.py
        if: matrix.part == 3
      - run: bash <(curl -s https://codecov.io/bash)
