name: ray-nightly
on: pull_request
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      work_dir: ${{ steps.get-dir.outputs.work_dir }}
    steps:
      - name: Init repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: get-dir
        run: echo "::set-output name=work_dir::$(echo $GITHUB_WORKSPACE)"
  test-ray-master:
    needs: configure
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKSPACE: ${{ needs.configure.outputs.work_dir }}
    container:
      image: rayproject/ray:nightly
    steps:
      - run: sudo apt update && sudo apt install -y build-essential
      - run: pip install -r requirements/requirements-no-engine.txt
      - name: Install HDF5
        run:  sudo apt install -y libhdf5-dev
      - shell: bash -l {0}
        run: pytest modin/experimental/xgboost/test/test_default.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_binary.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_default.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_indexing.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_iter.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_join_sort.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_map_metadata.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_reduction.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_udf.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_window.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_series.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_rolling.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_concat.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_groupby.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_reshape.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_general.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_io.py
      - shell: bash -l {0}
        run: python -m pytest modin/experimental/pandas/test/test_io_exp.py
