name: ray-nightly
on: pull_request
jobs:
  configure-host:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
  test-ray-master:
    needs: configure-host
    runs-on: ubuntu-latest
    container:
      image: rayproject/ray:nightly
      options: --user ${{ needs.configure-host.outputs.uid_gid }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: conda env update -f requirements/requirements-no-engine.yml --name base
      - shell: bash -l {0}
        run: pytest modin/experimental/xgboost/test/test_default.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_binary.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_default.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_indexing.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_iter.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_join_sort.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_map_metadata.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_reduction.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_udf.py
      - shell: bash -l {0}
        run: pytest modin/pandas/test/dataframe/test_window.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_series.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_rolling.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_concat.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_groupby.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_reshape.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_general.py
      - shell: bash -l {0}
        run: python -m pytest modin/pandas/test/test_io.py
      - shell: bash -l {0}
        run: python -m pytest modin/experimental/pandas/test/test_io_exp.py